- src: galaxyproject.galaxy
  version: 0.9.16
# - src: https://github.com/galaxyproject/ansible-galaxy.git
#   name: galaxyproject.galaxy
- src: galaxyproject.nginx
  version: 0.7.0
- src: galaxyproject.postgresql
  version: 1.0.3
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 2.0.0
- src: uchida.miniconda
  version: 0.3.0
# - src: https://github.com/usegalaxy-eu/ansible-galaxy-systemd
#   name: usegalaxy-eu.galaxy-systemd
#   version: py3
- src: usegalaxy_eu.galaxy_systemd
  version: 0.1.4
# - src: https://github.com/usegalaxy-eu/ansible-certbot
#   name: usegalaxy-eu.certbot
- src: usegalaxy_eu.certbot
  version: 0.1.5
- src: https://github.com/galaxyproject/ansible-galaxy-tools
  name: galaxyproject.galaxy-tools
# for slurm
- galaxyproject.repos
- galaxyproject.slurm
# for SANBI
- src: https://github.com/SANBI-SA/ansible-role-common.git
  name: sanbi-sa.common
- src: https://github.com/SANBI-SA/ansible-role-cephfs_client.git
  name: sanbi-sa.cephfs-client
- src: https://github.com/SANBI-SA/ansible-role-munge.git
  name: sanbi-sa.munge
- src: https://github.com/SANBI-SA/ansible-role-cloudns-acme.git
  name: sanbi-sa.cloudns-acme
- src: usegalaxy_eu.gxadmin
  version: 0.0.5
- src: https://github.com/pvanheus/ansible_galaxy_cleanup.git
  name: pvanheus.galaxy_cleanup$